#!/bin/bash

set -e -u

cp -a tests "${AUTOPKGTEST_TMP}"

PYTEST_OPTIONS="-k not \
test_ipv4 and not \
test_ipv6 \
"

for py3vers in $(py3versions -s); do
    echo
    echo "***************************"
    echo "*** Testing with ${py3vers}"
    echo "***************************"
    echo
    cd ${AUTOPKGTEST_TMP} && \
        echo -e "Content of current working folder:\n" && \
        ls -la && \
        echo -e "Running tests...\n" && \
        ${py3vers} -m pytest -s tests "${PYTEST_OPTIONS}" && \
        rm -rf .pytest_cache || exit 1
done

echo

exit 0
